version: '3.4'

services:
  web:
    build: ../study_buddy
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../study_buddy/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./study_buddy/envs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: event_planner_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data