# Generated by Django 4.1.4 on 2022-12-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='classroom.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='members.profile')),
            ],
        ),
    ]
