# Generated by Django 4.1.4 on 2022-12-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_myprofiledetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProfileDetails',
        ),
    ]
