# Generated by Django 4.1.4 on 2022-12-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_delete_myprofiledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='classroom.event')),
            ],
        ),
    ]
