# Generated by Django 4.1.4 on 2022-12-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import study_buddy.classroom.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0007_event_students_alter_event_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='classroom.event')),
                ('student', models.ForeignKey(default=study_buddy.classroom.models.logged_user, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
