# Generated by Django 4.1.4 on 2022-12-14 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0009_alter_joinedevent_event_alter_joinedevent_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='classroom.event'),
        ),
        migrations.AlterField(
            model_name='joinedevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
