# Generated by Django 4.1.4 on 2022-12-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_c',
        ),
        migrations.AddField(
            model_name='comment',
            name='event_c',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='classroom.event'),
            preserve_default=False,
        ),
    ]
