# Generated by Django 4.1.4 on 2022-12-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_remove_event_students_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_url',
        ),
    ]
