# Generated by Django 4.1.4 on 2022-12-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_alter_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_c',
        ),
        migrations.AlterField(
            model_name='comment',
            name='event_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.event'),
        ),
    ]
