# Generated by Django 4.1.4 on 2022-12-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_alter_comment_description_alter_comment_user_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.RemoveField(
            model_name='event',
            name='school',
        ),
        migrations.RemoveField(
            model_name='event',
            name='teacher',
        ),
        migrations.AddField(
            model_name='event',
            name='email_address',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.location'),
        ),
    ]
