# Generated by Django 4.1.4 on 2022-12-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
    ]
